### PR TITLE
Check for empty weather data

### PR DESCRIPTION
**Pull request by jojom4n**
It can rarely happen that CheckWX is down and/or transmits corrupted weather data (for example, QNH == 0). Should it happen so, RW still goes on modifying the mission file, DCS will load the .miz file by RW but clients will crash when entering the slot. 

Commit should avoid that, in these cases, RW will create a miz file with corrupt weather data. RW will still create a realweather.miz file (only because of batch file purposes), but the realweather.miz file should be unmodified with respect to the original mission.miz file.

### CODE REVIEW

**Comment by jojom4n** [comment]
Please, review the commit with salt, because I'm a C++ guy, not a Golang one. 

I applied the modification to my local RW because I had a miz file corrupted (and clients crashing) due to CheckWX transmitting  by mistake to RW all "0" parameters (including QNH).

**Comment by evogelsa** [comment]
This is great, thanks for the PR! I think it's a good idea to do some sanity checks on the data received from CheckWX, so let's keep working on this. However, we can probably clean it up a little. Are there any other weather data points that you think would be worth checking the validity of?

As for your original point comment, if the main issue is CheckWX API goes down sometimes, we should be able to more directly check this inside `GetWeather` by checking the response status (probably something I should have done in the first place). This project is due for a revisit anyways, so I will also open a new issue to address error handling in general as it could use some improvements.

I will work on getting these additions into your PR tonight or tomorrow as my time allows and then work on merging it.

**Comment by jojom4n** [comment]
Thanks for prompt feedback. 

Problem arose twice in last couple of days (never before) and I could verify that CheckWX had indeed some ongoing internal issues even by simply surfing on the official website (error 502).

I noticed that CheckWX had indeed transmitted almost most of METAR data with a "0" value. Here's one log:

2022/10/12 03:30:08 Updated wind:
2022/10/12 03:30:08     At 8000 meters:
2022/10/12 03:30:08             Speed m/s: 0.000
2022/10/12 03:30:08             Direction: 86
2022/10/12 03:30:08     At 0 meters:
2022/10/12 03:30:08             Speed m/s: 0.000
2022/10/12 03:30:08             Direction: 0
2022/10/12 03:30:08     At 2000 meters:
2022/10/12 03:30:08             Speed m/s: 0.000
2022/10/12 03:30:08             Direction: 42
2022/10/12 03:30:08 Fog Enabled: false
2022/10/12 03:30:08 Turbulence: 0
2022/10/12 03:30:08 Temperature Celsius: 0
2022/10/12 03:30:08 Fog Visibility meters: 0
2022/10/12 03:30:08 QNH mmHg: 0
2022/10/12 03:30:08 Dust Enabled: false
2022/10/12 03:30:08 Clouds:
2022/10/12 03:30:08     Preset:
2022/10/12 03:30:08     Base meters: 0

Now, I think QNH to 0 was the setting that upset DCS the most, since it cannot be never zeroed (temperature can, wind direction and speed can, etc.).

Lastly, I noticed another problem, but, given my very poor knowledge of Golang (PR was the first time I had business with this language), I could not solve it, and that happened when I intentionally set a non-existing ICAO in config.json and RW exited with an error message without proceeding to copy mission.miz into a clean unaltered realweather.miz file (that could be a problem by using batch file).

I concur your idea of adding checks inside GetWeather, it's a much more elegant solution than mine and the one I would have opted for, if only I have had the required skills with the language. 

I guess the important thing, to preserve running batch files (like the one I customised, and I guess other users are doing the same too) is that RW, even when failing those checks, should nonetheless create a realweather.miz (even if only an unmodified copy of mission.miz).

For example, my batch file moves each one of my three missions (one for each daytime) into RW's folder, calls RW, then moves realweather.miz back into DCS' mission folder and renames it, before proceeding with mission rotation. Should realweather.miz not exist, batch file could not move anything and server would simply crash, being unable to load a valid mission.

**Comment by evogelsa** [comment]
> Problem arose twice in last couple of days (never before) and I could verify that CheckWX had indeed some ongoing internal issues even by simply surfing on the official website (error 502).

Thanks for the details. Good to know that you were able to confirm that CheckWX being down was actually the problem since as discussed earlier that should only take an easy check of the response status to fix.

> I noticed that CheckWX had indeed transmitted almost most of METAR data with a "0" value. Here's one log:

I doubt the API response is actually returning zeroed data, but rather the response is invalid (e.g. you noted seeing 502s when trying to access the webpage). One of the features of Go is that all variables/data types have a default value, which for numeric types this is zero, so since the response is invalid the weather data struct is not changed away from its default values.

> Lastly, I noticed another problem, but, given my very poor knowledge of Golang (PR was the first time I had business with this language), I could not solve it, and that happened when I intentionally set a non-existing ICAO in config.json and RW exited with an error message without proceeding to copy mission.miz into a clean unaltered realweather.miz file (that could be a problem by using batch file).

Noted, I may be able to address this with #8. You're correct that the program really shouldn't panic for simple errors, but if there is a fatal error like an invalid ICAO, it should give a better error message to help with troubleshooting. Errors in the config file should probably be considered fatal, but these options should be validated the first time the program is run so you know right away if/where there are issues.

> I concur with your idea of adding checks inside GetWeather, it's a much more elegant solution than mine and the one I would have opted for, if only I had the required skills with the language.

Don't worry about implementing this, I should be able to add the directly to your pull request before merging.

> I guess the important thing, to preserve running batch files (like the one I customised, and I guess other users are doing the same too) is that RW, even when failing those checks, should nonetheless create a realweather.miz (even if only an unmodified copy of mission.miz).
>
> For example, my batch file moves each one of my three missions (one for each daytime) into RW's folder, calls RW, then moves realweather.miz back into DCS' mission folder and renames it, before proceeding with mission rotation. Should a "realweather.miz" file not exist at all, my customised batch file could not move anything and server would simply crash, being unable to load a valid mission.

Fair enough, this is how our run scripts (and the one in the examples of this repo) worked too, so in the case of a non-fatal runtime error like the CheckWX service being down, I agree that the program should just copy the input file to the output and log it. I'll either get this addressed in #8 as well or open a new issue for it later.

**Comment by jojom4n** [comment]
> I doubt the API response is actually returning zeroed data, but rather the response is invalid (e.g. you noted seeing 502s when trying to access the webpage). One of the features of Go is that all variables/data types have a default value, which for numeric types this is zero, so since the response is invalid the weather data struct is not changed away from its default values.

I see. That's interesting and quite different from C++, where uninitialized variable gets a random value depending on the garbage present on the memory address the variable was allocated to.
I guess it should be sufficient to initialize RW's variables with a rationale values, just in case it cannot update METAR due to CheckWX's internal issues (QNH, for example, could be defaulted to common 2992).
 
> Noted, I may be able to address this with #8. You're correct that the program really shouldn't panic for simple errors, but if there is a fatal error like an invalid ICAO, it should give a better error message to help with troubleshooting. Errors in the config file should probably be considered fatal, but these options should be validated the first time the program is run so you know right away if/where there are issues.

That sounds good.

> Don't worry about implementing this, I should be able to add the directly to your pull request before merging.

Thank you very much. RW is a great tool indeed, I love how it gives pilots a realistic environment without any effort for mission designer.

**Comment by jojom4n** [comment]
Thank you very much!

**Pull request merged**
